### PR TITLE
Np ptd

### PR DESCRIPTION
**Pull request by nathanpabst**
branch = np_ptd
here are the notes from the ticket...
In dom.js, name the function printToDom
Set a variable that grabs an element by ID. 
Example: const outputDiv = document.getElementById('dinos');
Then set that elements innerHTML to our domStringBuilder function with the array of info we want passed into it
Example: outputDiv.innerHTML = domString(dinoArray);
The function should look something like this:
const printToDom = (dinoArray) => { outputDiv.innerHTML = domString(dinoArray); };
Then export it for use throughout the rest of the project
Example module.exports = printToDom;

### CODE REVIEW

**Comment by briankw23** [comment]
🇹🇭

**Comment by briankw23** [comment]
good

**Comment by ledugani** [comment]
👍

**Comment by Junochop** [comment]
good

**Pull request merged**
